### PR TITLE
b_cfn_api_v2 extended

### PR DESCRIPTION
**Pull request by sandor1cloudvisor**
- enable_default_stage method modified, when a default stage is created
access logs are collected to a loggroup
- tested (logs created, I was able to use it, unit test was all green)

### CODE REVIEW

**Comment by laimonassutkus** [comment]
Thanks, @sandor1cloudvisor for using this library and for raising a pull request. I have slightly modified it to make it more configurable and backward compatible. Please review this commit: https://github.com/Biomapas/B.CfnApiV2/commit/b15892e11daaa4d8f54a105d21080a4099ef56cf.

**Comment by laimonassutkus** [comment]
I am closing this pull request with status "resolved".

**Comment by sandor1cloudvisor** [comment]
@laimonassutkus Yes, it make more sense as you modified, making the logging optional and formatting the log config string :)

**Comment by laimonassutkus** [comment]
Awesome!

**Pull request closed without merging**
